(part "KF7_62"
    (packageRef "SHDR5W120P0X762_1X5_3810X1200X1240P")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "5") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Manufacturer_Name" "CIXI KEFA ELECTRONICS")
    (property "Manufacturer_Part_Number" "KF7.62")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "RS_Part_Number" "")
    (property "RS_Price/Stock" "")
    (property "Description" "D")
    (property "Datasheet_Link" "http://en.cnkefa.com/uploads/2016/07/181706523348.pdf")
    (property "symbolName1" "KF7_62")
)
